input {
  file {
    path => "/host_logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  date {
    match => ["asctime", "yyyy-MM-dd HH:mm:ss,SSS"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "python-app-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}